#!/usr/bin/env php
<?php

require_once __DIR__ .'/vendor/autoload.php';

/**
 * Base Project Path
 * @var BASE_PATH string
 */

use Razer\Console\Console;
use Razer\Console\Kernel\Kernel;

define('BASE_PATH', __DIR__);

/**
 * Init the console app
 */
$console = new Console();

/**
 * Register the kernel
 */
$kernel = new Kernel(BASE_PATH);

/**
 * Make the kernel and run the cosnsole
 */

 $kernel = $kernel->make($console->arguments());

 /**
  * Run the Kernel
  */

  $kernel->run();
